config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'kotobas#index'
  resources :kotobas do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :kotoba  
  belongs_to :user  
end

app/models/kotoba.rb
class Kotoba < ApplicationRecord
  validates :text, presence: true
  validate :check_forbidden_words

  belongs_to :user
  has_many :comments
  
  def soft_delete
    self.update_attribute(:delete_at, Time.current)
  end
  
    private
  
    def check_forbidden_words
      forbidden_words = ["死ね", "殺す", "殺し"]
      if forbidden_words.any? { |word| text.include?(word) }
        errors.add(:text, "使用できない言葉が含まれています")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :kotobas
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
     redirect_to "/kotobas/#{comment.kotoba.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, kotoba_id: params[:kotoba_id])
  end
end

app/controllers/kotobas_controller.rb
class KotobasController < ApplicationController
  before_action :set_kotoba, only:[:show, :edit, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @kotobas = Kotoba.all
  end

  def new
    @kotoba = Kotoba.new
  end

  def create
    Kotoba.create(kotoba_params)
    redirect_to root_path
  end

  def edit
    
  end

  def update
    kotoba = Kotoba.find(params[:id])
    kotoba.update(kotoba_params)
    redirect_to root_path
  end

  def destroy
    kotoba = Kotoba.find(params[:id])
    kotoba.destroy
    redirect_to root_path
  end


  def show
    @user = @kotoba.user
    @comment = Comment.new
    @comments = @kotoba.comments
  end

  def delete_kotoba
    kotoba = Kotoba.find(params[:id])
    kotoba.destroy
    current_user.increment!(:delete_count)
    redirect_to root_path
    # ...
  end

  private
  def kotoba_params
    params.require(:kotoba).permit(:name, :text).merge(user_id: current_user.id)
  end

  def set_kotoba
    @kotoba = Kotoba.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @kotobas = current_user.kotobas
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def truncate_with_newline(text, length: 35, omission: '...')
      if text.include?("\n")
        first_line = text.split("\n").first
      truncated_first_line = first_line.truncate(length, omission: omission)
      truncated_first_line += "..." if first_line.length > length || text.split("\n").size > 1
      truncated_first_line
      else
        text.truncate(length, omission: omission)
      end
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/kotobas_helper.rb
module KotobasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kotobas/edit.html.erb
<body>

<main>
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @kotoba, local: true) do |form| %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>
</main>

</body>

app/views/kotobas/index.html.erb
<body>

<main>

<section id="section2" class="section">
<div class="contents row">
  <div class="content_kotoba">
   <% @kotobas.each do |kotoba| %>
      <%= link_to kotoba_path(kotoba.id), class: "content_link" do %>
        <div class="content_post" style="background-image:mitei ">
          <div class="leaf-1"></div> 
          <div class="content_post_box">
            <div class="content_post_time">
              <p><%= kotoba.created_at.in_time_zone.strftime('%Y-%m-%d %H:%M') %></p>
            </div> 
            <div class="content_post_main">
              <p><%= simple_format(truncate_with_newline(kotoba.text)) %></p>
            </div>
          </div> 
        </div>
     <% end %>   
    <% end %> 
  </div>
</div>

</section>

</main>

</body>

app/views/kotobas/new.html.erb
<body>

<main>
  <div class="contents row">
   <div class="container">
     <h3>投稿する</h3>
     <%= form_with(model: @kotoba, local: true) do |form| %>
       <%= form.text_area :text, placeholder: "text", rows: "10" %>
        <%= form.submit "SEND" %>
     <% end %>
   </div>
  </div>
</main>

</body>

app/views/kotobas/show.html.erb
<body>

<main>

<section id="section2" class="section">
<div class="contents row">
  <div class="content_kotoba">
        <div class="content_show" style="background-image:mitei ">
          <div class="leaf-1"></div> 
          <div class="content_post_box">
            <div class="content_post_time">
              <p><%= @kotoba.created_at.in_time_zone.strftime('%Y-%m-%d %H:%M') %></p>
            </div> 
            <div class="content_post_main">
              <p><%= simple_format(@kotoba.text) %></p>
            </div>
          </div> 
        </div>
  </div>
</div>
<div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@kotoba, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "はげましの言葉を送る", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ 励ましの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
   <div class="comments">
      <h4>＜励ましの言葉＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
</div>

<div class="show_boxes">
  <% if user_signed_in?%>
       <% if current_user.id == @user.id %>
        <div class="show_box">
           <%= link_to '編集', edit_kotoba_path(@kotoba.id) %>
        </div>  
        <div class="show_box">
           <%= link_to '削除', kotoba_path(@kotoba.id),data: { turbo_method: :delete } %>
        </div>  
        <div class="show_box">
           <%# <%= link_to '滔々', delete_item_kotoba_path(@kotoba), data: { turbo_method: :delete } %> 
        </div> 
       <% end %>   
  <% end %>          
</div>  

</section>

</main>

</body>


 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title>Kotonoha</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ここにサイト説明を入れます">
    <%# <link rel="stylesheet" href="css/style.css"> %>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>
  

  <body>
    <% unless controller_name == 'sessions' && action_name == 'new' || (controller_path == 'devise/registrations' && action_name == 'new')  %>
     <header>
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">言の葉滔々</a></h1>
         <% if user_signed_in? %>
          <div class="right_contents">
            <div class="user_nav grid-6">
              <%= link_to current_user.nickname, "/users/#{current_user.id}" %>
            </div>
            <div class="posting">
              <%= link_to "投稿する", new_kotoba_path, class: "post" %>
            </div>
            <div class="log_out">
               <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
            </div>
          </div>
         <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
         <% end %>
      </div>
     </header>
    <% end %>

    <%= yield %>
    <footer>
      <footer>
        <small>Copyright&copy; <a href="index.html">Artist Web Site</a> All Rights Reserved.</small>
        <span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
      </footer>

          <!--ページの上部へ戻るボタン-->
          <div class="pagetop"><a href="#"><i class="fas fa-angle-double-up"></i></a></div>

            <!--開閉ボタン（ハンバーガーアイコン）-->
          <div id="menubar_hdr">
            <span></span><span></span><span></span>
          </div>

            <!--jQueryの読み込み-->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

            <!--lightbox用jsファイルの読み込み-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox-plus-jquery.min.js"></script>

            <!--このテンプレート専用のスクリプト-->
            <script src="js/main.js"></script>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<body>

<main>

<section id="section2" class="section">
<div class="contents row">
  <div class="content_kotoba">
   <% @kotobas.each do |kotoba| %>
      <%= link_to kotoba_path(kotoba.id), class: "content_link" do %>
        <div class="content_post" style="background-image:mitei ">
          <div class="leaf-1"></div> 
          <div class="content_post_box">
            <div class="content_post_time">
              <p><%= kotoba.created_at.in_time_zone.strftime('%Y-%m-%d %H:%M') %></p>
            </div> 
            <div class="content_post_main">
              <p><%= simple_format(truncate_with_newline(kotoba.text)) %></p>
            </div>
          </div> 
        </div>
     <% end %>   
    <% end %> 
  </div>
</div>
</section>

</main>

</body>